<?php

/**
 * @file
 * Code for the ma_chinese feature.
 */

include_once 'ma_chinese.features.inc';

/**
 * Alter the list of project to be updated by Localization Update.
 *
 * L10n_update uses the same list of projects as update module. Using this hook
 * the list can be altered. This hook is typically used to alter the following
 * values from the .info file:
 *  - interface translation project
 *  - l10n path.
 *
 * @param array $projects
 *   Array of projects.
 */
function ma_chinese_l10n_update_projects_alter(array &$projects) {

  // Set the path to the custom module translation files if not already set.
  if (isset($projects['ma_chinese'])) {
    $path = drupal_get_path('module', 'ma_chinese');
    $projects['ma_chinese']['info']['l10n path'] = $path . '/translations/%language.po';

    // With this hook it is also possible to add a new project which does not
    // exist as a real module or theme project but is treated by the localization
    // update module as one. The below data is the minimum to be specified.
    // As in the previous example the 'l10n path' element is optional.
    $projects['ma_chinese_contrib'] = array(
      'project_type'  => 'module',
      'name' => 'ma_chinese_contrib',
      'info' => array(
        'name' => 'Mukurtu Chinese Contrib',
        'version' => '7.x-1.0',
        'core' => '7.x',
        'l10n path' => $path . '/translations/contrib.%language.po',
      ),
    );
    $projects['ma_chinese_custom'] = array(
      'project_type'  => 'module',
      'name' => 'ma_chinese_custom',
      'info' => array(
        'name' => 'Mukurtu Chinese Custom',
        'version' => '7.x-1.0',
        'core' => '7.x',
        'l10n path' => $path . '/translations/custom.%language.po',
      ),
    );
  }
}

